version: '3'
services:
  api:
    build: .
    image: 'codegov/code-gov-api:latest'
    container_name: 'code-gov-api'
    ports:
      - "3000:3000"
    environment:
      - NEW_RELIC_KEY='not_a_key'
      - GITHUB_API_KEY='not-a-key'
      - ES_HOST=http://elastic:changeme@elasticsearch:9200
      - ES_URI=http://elastic:changeme@elasticsearch:9200
      - ES_PORT=9200
      - ES_USER=elastic
      - ES_PASSWORD=changeme
      - NODE_ENV='dev'
      - USE_HSTS=false
      - HSTS_MAX_AGE=31536000
      - HSTS_PRELOAD=false
    depends_on:
      - elasticsearch
    volumes:
      - .:/usr/src/app
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:5.6.9"
    container_name: 'code-gov-data'
    ports:
      - "9200:9200"
  UI: 
    build: ../code-gov-front-end/.
    image: code-gov-ui
    container_name: 'code-gove-ui'
    ports:
      - "8081:80"
  Harvester: 
    command: npm start
    build: ../code-gov-harvester/.
    image: code-gov-harvester
    container_name: 'code-gov-harvester'
    environment:
      - ES_URI=http://elastic:changeme@elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - "8082:100"
      